In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [24]:
df = pd.read_csv('Titanic-Dataset.csv')[['Age','Pclass','SibSp','Parch','Fare','Survived']]

In [25]:
# basically feature construction grows with experience

In [26]:
df.dropna(inplace=True)

In [27]:
df.head()

    Age  Pclass  SibSp  Parch     Fare  Survived
0  22.0       3      1      0   7.2500         0
1  38.0       1      1      0  71.2833         1
2  26.0       3      0      0   7.9250         1
3  35.0       1      1      0  53.1000         1
4  35.0       3      0      0   8.0500         0

In [28]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [29]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [30]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

# Applying Feature Construction

In [31]:
X['Family_size'] = X['SibSp']+X['Parch']+1

In [32]:
X.head(1)

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2

In [39]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num > 1 and num <= 4:
        #small family
        return 1
    elif num <= 0:
        #invalid input
        return -1
    else:
        #large family
        return 2

In [42]:
myfunc(4)

1

In [43]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [44]:
X.head(1)

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1

In [45]:
X.drop(columns=['SibSp','Family_size','Parch'], inplace=True)

In [46]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [47]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy', cv=20))

np.float64(0.7003174603174602)

# Feature Splitting

In [48]:
df = pd.read_csv('Titanic-Dataset.csv')

In [50]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [52]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [53]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [54]:
df[['Title', 'Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]